services:
  - type: web
    name: physics-code-academy
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: srujan sathe
      - key: ADMIN_PASSWORD
        value: srujan@2004
      - key: DATABASE_URL
        fromDatabase:
          name: physics-db
          property: connectionString

databases:
  - name: physics-db
    plan: free
    region: oregon
